Homework3:	IntArray.o Homework3.o HelperFunctions.o
	g++ Homework3.o IntArray.o HelperFunctions.o -o Homework3

Homework3.o:	IntArray.h HelperFunctions.h Homework3.cc
	g++ -c Homework3.cc

HelperFunctions.o:	HelperFunctions.h HelperFunctions.cc
	g++ -c HelperFunctions.cc

IntArray.o:	IntArray.h IntArray.cc
	g++ -c IntArray.cc