#ifndef INCLUDED_Constants
#define INCLUDED_Constants

#define BASESTRINGSIZE 1024
#define ROUTERIPFILE "/home/sixer601/CPSC464/RouterProject/routerIP.txt"
#define ROUTERIPFILE2 "/home/students/smbeardsley/RouterProject/routerIP.txt"
#define TEMPFILE "/tmp/test2output.txt"
#define ROUTERPORTNUMBER 2048
#define MYMAXCONNECTIONS 100
#define MAXENTRIES 500
#define SIGNALSTRENGTH 25

#define BROADCASTIPADDRESS "0"
#define BROADCASTPORT 0

#define ROUTERINITIALMESSAGEHEADERCHARACTER 'r'
#define DEVICEINITIALMESSAGEHEADERCHARACTER 'd'

#define DELIMITER "_"
#define IPPORTSEPARATOR ":"
#define BEGINMESSAGECHAR "M"
#define ENDMESSAGECHAR "m"
#define BEGINSENDERCOORDINATESCHAR "C"
#define ENDSENDERCOORDINATESCHAR "c"
#define BEGINSENDERADDRESSCHAR "S"
#define ENDSENDERADDRESSCHAR "s"
#define BEGINRECIPIENTADDRESSCHAR "R"
#define ENDRECIPIENTADDRESSCHAR "r"
#define BEGINROUTINGTABLECHAR "T"
#define ENDROUTINGTABLECHAR "t"
#define BEGINENTRYCHARACTER "E"
#define ENDENTRYCHARACTER "e"
#define BEGINDESTINATIONCHARACTER "D"
#define ENDDESTINATIONCHARACTER "d"
#define BEGINFIRSTHOPCHARACTER "F"
#define ENDFIRSTHOPCHARACTER "f"
#define BEGINDISTANCECHARACTER "X"
#define ENDDISTANCECHARACTER "x"
#define EMPTYROUTINGTABLE "Tt"

#define ROUTINGTABLECOLUMN1HEADER "Destination Address"
#define ROUTINGTABLECOLUMN2HEADER "First Hop Address"
#define ROUTINGTABLECOLUMN3HEADER "Distance"

#endif
